# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa218a71938e123c05e9232311b188a098d7dc1882ba4ae845e9d59e75645ec76ac36298c772fa69fcb38f9a16a798c38a56973bea3ff7c5d312abd60b0cad33

test:
  secret_key_base: 1c390b40226fdfe9c093f9a0a6a6d853f81e3e1a8a34dbf446cf378b55966889f287b047cf477389a3a54fe7fbc82ccdd534a29f4bed2b545dc2945d434f2d49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
